# Generated by Django 3.2.16 on 2023-06-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20230608_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Congratulation',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
